#!/bin/sh
export LD_LIBRARY_PATH=/run/opengl-driver/lib/:$(nix-instantiate --eval -E 'with import <nixpkgs> {}; lib.makeLibraryPath (with xorg; [libX11 libXcursor libXxf86vm libXi])' | tr -d '"')
exec path/to/alacritty